# Generated by Django 5.0.6 on 2024-05-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_prices',
            field=models.FloatField(max_length=10),
        ),
    ]
