# Generated by Django 5.0.6 on 2024-05-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_customer_zipcode_alter_product_selling_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling_prices',
            field=models.FloatField(),
        ),
    ]
